server:
  port: 8081

spring:
  application:
    name: auth-server
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      
logging:
  level:
    "[org.springframework.security]": DEBUG
    "[org.springframework.web]": DEBUG
