server:
  port: 8081
  
spring:
  application:
    name: auth-server
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:${server.port}
          jwk-set-uri: http://localhost:${server.port}/oauth2/jwks
      client:
        registration:
          my-client:
            client-id: my-client
            client-secret: my-secret
            scope: openid
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:${server.port}/login/oauth2/code/my-client
            client-authentication-method: client_secret_basic
        provider:
          my-provider:
            authorization-uri: http://localhost:${server.port}/oauth2/authorize
            token-uri: http://localhost:${server.port}/oauth2/token
            user-info-uri: http://localhost:${server.port}/userinfo
            jwk-set-uri: http://localhost:${server.port}/oauth2/jwks
            issuer-uri: http://localhost:${server.port}
            
logging:
  level:
    "[org.springframework.security]": DEBUG
    "[org.springframework.web]": DEBUG