spring:
  application:
    name: auth-server
#  security:
#    oauth2:
#      client:
#        registration:
#          my-client:
#            client-id: my-client
#            client-secret: my-secret
#            scope: openid
#            authorization-grant-type: authorization_code
#            redirect-uri: http://localhost:8080/login/oauth2/code/my-client
#            client-authentication-method: client_secret_basic
#        provider:
#          my-provider:
#            authorization-uri: http://localhost:8080/oauth2/authorize
#            token-uri: http://localhost:8080/oauth2/token
#            user-info-uri: http://localhost:8080/userinfo
#            jwk-set-uri: http://localhost:8080/oauth2/jwks
#            issuer-uri: http://localhost:8080
logging:
  level:
    "[org.springframework.security]": DEBUG
    "[org.springframework.web]": DEBUG